name: current
on:
  workflow_dispatch:
jobs:
  shared:
    runs-on: ubuntu-latest
    steps:
    - name: Drop old current release
      uses: luccas-freitas/delete-older-releases@v0.0.1
      with:
        owner: stellartrails
        repos: stellartrails-website
        keep_latest: 0
        delete_tag_pattern: current
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
  macos:
    needs: shared
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GIT_TOKEN }}
    - name: Set up Java 21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Build with Maven
      run: |
        git clone https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_TOKEN }}@github.com/stellartrails/stellartrails
        cd stellartrails
        mvn -B -DskipTests -DskipITs -ntp -P macos package
        cp macos/target/*.dmg ../StellarTrails.dmg
    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: current
        files: |
          StellarTrails.dmg
  windows:
    needs: shared
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GIT_TOKEN }}
    - name: Set up Java 21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Build with Maven
      run: |
        git clone https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_TOKEN }}@github.com/stellartrails/stellartrails
        cd stellartrails
        mvn -B -DskipTests -DskipITs -ntp -P windows package
        cp windows/target/*.msi ../StellarTrails.msi
    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: current
        files: |
          StellarTrails.msi
